// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-H_zPts9SXz1QgY9CuSMPZH7Stcd1FX8',
    appId: '1:472164940476:web:3bc70c7142f7b5cb8d2eb9',
    messagingSenderId: '472164940476',
    projectId: 'transcribe-app-c9031',
    authDomain: 'transcribe-app-c9031.firebaseapp.com',
    storageBucket: 'transcribe-app-c9031.appspot.com',
    measurementId: 'G-16RHXF90VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzDYPEZI1UmNZfdr0pdSXSuXGBkeQron4',
    appId: '1:472164940476:android:b99a7efaed5a1ed68d2eb9',
    messagingSenderId: '472164940476',
    projectId: 'transcribe-app-c9031',
    storageBucket: 'transcribe-app-c9031.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl-bjFsnKxsWjERZSXpESGKn6_lmbNn5A',
    appId: '1:472164940476:ios:0d6ce6630ba99b438d2eb9',
    messagingSenderId: '472164940476',
    projectId: 'transcribe-app-c9031',
    storageBucket: 'transcribe-app-c9031.appspot.com',
    iosBundleId: 'com.example.transcribe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl-bjFsnKxsWjERZSXpESGKn6_lmbNn5A',
    appId: '1:472164940476:ios:341d78d3d2d355a58d2eb9',
    messagingSenderId: '472164940476',
    projectId: 'transcribe-app-c9031',
    storageBucket: 'transcribe-app-c9031.appspot.com',
    iosBundleId: 'com.example.transcribe.RunnerTests',
  );
}
